---
- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user and add to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    create_home: true
  tags:
    - user
