---
- name: Install snapper
  pacman:
    name: snapper
    state: present

- name: Install snapper config
  template:
    src: templates/config.j2
    dest: "/etc/snapper/configs/{{ item.name }}"
  register: install_snapper
  loop: "{{ snapper.configs }}"


- name: Install snapper config list
  template:
    src: templates/snapper.j2
    dest: /etc/conf.d/snapper

- name: Create first snapshot
  command:
    cmd: "snapper -c {{ item.name }} create"
  when: install_snapper.results[config_idx].changed == true
  loop: "{{ snapper.configs }}"
  loop_control:
    index_var: config_idx

- name: Enable snapper timers
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - snapper-timeline.timer
    - snapper-cleanup.timer
