---
- name: Install snapper
  pacman:
    name: snapper
    state: present

- name: Install snapper config
  template:
    src: templates/root.j2
    dest: /etc/snapper/configs/root
  register: install_snapper

- name: Install snapper config list
  copy:
    src: files/snapper
    dest: /etc/conf.d/snapper

- name: Create first snapshot
  command:
    cmd: snapper -c root create
  when: install_snapper.changed == true

- name: Enable snapper timers
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - snapper-timeline.timer
    - snapper-cleanup.timer
