---
- name: Install shell-related pacman packages
  pacman:
    name: "{{ packages.shell.pacman }}"

- name: Install shell-related AUR packages
  kewlfft.aur.aur:
    name: "{{ packages.shell.aur }}"
  become: true
  become_user: aur_builder

- name: Check if fish plugins installed
  command:
    cmd: "/usr/bin/fish -c fisher list"
  become: true
  become_user: "{{ user.name }}"
  register: fish_list
  tags:
    - fish

- name: Install fish plugins via fisher
  command:
    cmd: "/usr/bin/fish -c fisher update"
  become: true
  become_user: "{{ user.name }}"
  when: not fish_list.stdout
  tags:
    - fish
