user:
  name: bazyli
  group: bazyli
  email: bazyli@cyran.dev
  shell: /usr/bin/fish

dotfiles:
  repo_https: https://github.com/bcyran/dotfiles.git
  repo_ssh: git@github.com:bcyran/dotfiles.git

packages:
  base:
    pacman:
      - base-devel
      - bc
      - curl
      - fish
      - git
      - htop
      - linux-headers
      - man-db
      - man-pages
      - ncdu
      - neovim
      - networkmanager
      - pacman-contrib
      - powertop
      - reflector
      - rsync
      - terminus-font
      - tmux
      - wget
    aur:
      - downgrade
  shell:
    pacman:
      - bat
      - btop
      - exa
      - fzf
      - fd
      - fisher
      - git-delta
      - inetutils
      - ranger
      - ripgrep
      - the_silver_searcher
      - tmux
      - tree
      - figlet
      - neofetch
      - zoxide
    aur:
      - virtualfish
  desktop:
    pacman:
      - alacritty
      - alsa-utils
      - dunst
      - file-roller
      - firefox
      - gnome-calculator
      - gnu-free-fonts
      - gthumb
      - gvfs
      - hyprland
      - inotify-tools
      - lxappearance
      - mesa
      - nm-connection-editor
      - noto-fonts-cjk
      - noto-fonts-emoji
      - pavucontrol
      - pipewire-alsa
      - pipewire-audio
      - pipewire-pulse
      - playerctl
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - rustup
      - swayidle
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - tlp
      - ttf-dejavu
      - ttf-font-awesome
      - ttf-jetbrains-mono-nerd
      - ttf-roboto
      - tumbler
      - waybar
      - wayland
      - wireplumber
      - wl-clipboard
      - wmctrl
      - xdg-user-dirs
      - zathura
      - zathura-pdf-mupdf
    aur:
      - adw-gtk3
      - appimagelauncher
      - batify-git
      - grimblast-git
      - light
      - nwg-look
      - onagre-git
      - satty-bin
      - swaylock-effects
      - swww
      - timewall-bin
      - ttf-icomoon-feather
      - wdisplays
      - we10x-icon-theme-git
      - wlsunset
      - xcursor-breeze
      - xdg-desktop-portal-hyprland
  daily:
    pacman:
      - calibre
      - gimp
      - gnucash
      - gparted
      - imagemagick
      - keepassxc
      - kooha
      - libreoffice-fresh
      - libreoffice-fresh-pl
      - obsidian
      - signal-desktop
      - transmission-gtk
      - vlc
    aur:
      - anydesk-bin
      - megasync-bin
      - philipstv
      - philipstv-gui
      - portfolio-performance-bin
      - showmethekey
      - spotify
  develop:
    pacman:
      - docker
      - httpie
      - jq
      - python-black
      - python-isort
      - python-pip
      - python-poetry
      - python-pynvim
      - python-tox
      - python-virtualenv
      - rustup
    aur: []
