---
- name: Install logiops
  kewlfft.aur.aur:
    use: yay
    name: logiops-git
  become: true
  become_user: aur_builder

- name: Install logiops config
  copy:
    src: files/logid.cfg
    dest: /etc/logid.cfg

- name: Enable logid service
  systemd:
    name: logid.service
    state: started
    enabled: true
