---
- name: Create getty1 configuration dir
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
  tags:
    - autologin

- name: Setup autologin
  template:
    src: templates/autologin.conf
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
  tags:
    - autologin
