---
- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user and add to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    shell: "{{ user.shell }}"
    create_home: true
  register: create_user
  tags:
    - user

- name: Prompt for user password
  pause:
    prompt: "Please enter password for user '{{ user.name }}'"
    echo: false
  register: password_prompt
  when: create_user.changed
  tags:
    - user

- name: Set user password
  user:
    name: "{{ user.name }}"
    password: "{{ password_prompt.user_input | password_hash('sha512') }}"
    update_password: always
  when: create_user.changed
  tags:
    - user
