---
- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

- name: Create user and add to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    shell: "{{ user.shell }}"
    create_home: true
  register: create_user
  tags:
    - user

- name: Set user password
  user:
    name: "{{ user.name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: always
  when: create_user.changed
  tags:
    - user
