---
- name: Install DDC/CI driver
  kewlfft.aur.aur:
    name: "ddcci-driver-linux-dkms"
  become: true
  become_user: aur_builder
  tags:
    - backlight

- name: Create systemd backlight service
  copy:
    src: files/ddcci-backlight.service
    dest: /etc/systemd/system/ddcci-backlight.service
  tags:
    - backlight

- name: Enable and start systemd backlight service
  systemd:
    name: ddcci-backlight.service
    state: started
    enabled: true
  tags:
    - backlight
