---
- name: Install desktop-related pacman packages
  pacman:
    name: "{{ packages.desktop.pacman + host.gfx_packages | default([]) }}"

- name: Install desktop-related AUR packages
  kewlfft.aur.aur:
    use: yay
    name: "{{ packages.desktop.aur }}"
  become: true
  become_user: aur_builder

- name: Add user to video group
  user:
    name: "{{ user.name }}"
    groups: video
    append: yes

- include_tasks: backlight.yml
- include_tasks: sleeplock.yml
