---
- name: Install spicetify
  kewlfft.aur.aur:
    use: yay
    name: spicetify-cli
  become: true
  become_user: aur_builder
  tags:
    - spicetify

- name: Own spotify install
  file:
    path: /opt/spotify
    owner: "{{ user.name }}"
    recurse: true
  tags:
    - spicetify

- name: Initialize spicetify
  command:
    cmd: spicetify
    creates: "/home/{{ user.name }}/.config/spicetify"
  become_user: "{{ user.name }}"
  tags:
    - spicetify

- name: Copy the config file
  template:
    src: files/config-xpui.ini.j2
    dest: "/home/{{ user.name }}/.config/spicetify/config-xpui.ini"
  tags:
    - spicetify

- name: Create spicetify backup
  command:
    cmd: spicetify backup
    creates: "/home/{{ user.name }}/.config/spicetify/Backup/xpui.spa"
  become_user: "{{ user.name }}"
  tags:
    - spicetify

- name: Check if One Dark theme installed
  stat:
    path: "/home/{{ user.name }}/.config/spicetify/Themes/OneDark"
  register: onedark_installed
  tags:
    - spicetify

- name: Download One Dark theme
  unarchive:
    remote_src: true
    src: https://codeload.github.com/Frostplexx/spicetify-one-dark/zip/refs/heads/main
    dest: /tmp
    creates: /tmp/spicetify-one-dark-main
  when: not onedark_installed.stat.exists
  tags:
    - spicetify

- name: Copy One Dark theme
  copy:
    remote_src: true
    src: /tmp/spicetify-one-dark-main/OneDark/
    dest: "/home/{{ user.name }}/.config/spicetify/Themes/OneDark"
    directory_mode: true
    owner: "{{ user.name }}"
  when: not onedark_installed.stat.exists
  tags:
    - spicetify

- name: Copy One Dark extension
  copy:
    remote_src: true
    src: /tmp/spicetify-one-dark-main/js/
    dest: "/home/{{ user.name }}/.config/spicetify/Extensions"
    owner: "{{ user.name }}"
  when: not onedark_installed.stat.exists
  tags:
    - spicetify

- name: Apply settings
  command:
    cmd: spicetify apply
  become_user: "{{ user.name }}"
  tags:
    - spicetify
