---
- name: Create the `aur_builder` user
  user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags:
    - aur

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - aur

- name: Setup makepkg
  lineinfile:
    path: /etc/makepkg.conf
    search_string: "{{ item.search }}"
    line: "{{ item.line }}"
  loop:
    - search: "COMPRESSXZ"
      line: "COMPRESSXZ=(xz -c -z - --threads=0)" 
    - search: "MAKEFLAGS"
      line: 'MAKEFLAGS="-j$(nproc)"'
  tags:
    - aur

- name: Install paru
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  become: true
  become_user: aur_builder
  tags:
    - aur

- name: Copy paru config
  copy:
    src: files/paru.conf
    dest: /etc/paur.conf
  tags:
    - aur
