---
- name: Install pacman configuration
  template:
    src: files/pacman.conf.j2
    dest: /etc/pacman.conf
  tags:
    - pacman

- name: Install base packages
  pacman:
    name: "{{ packages.base.pacman }}"
    state: present
    update_cache: true
  tags: 
    - pacman

- name: Copy reflector configuration
  copy:
    src: files/reflector.conf
    dest: /etc/xdg/reflector/reflector.conf
  tags:
    - pacman

- name: Enable automatic pacman mirorrlists refreshing
  systemd:
    name: reflector.timer
    state: started 
    enabled: true
  tags:
    - pacman
