---
- name: Create the `aur_builder` user
  user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags:
    - yay

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - yay

- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: true
  become_user: aur_builder
  tags:
    - yay
