---
- name: Install bluetooth packages
  pacman:
    name:
      - blueman
      - bluez
      - bluez-utils
    state: present
  tags:
    - bluetooth

- name: Auto enable bluetooth
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: ".*AutoEnable.*"
    line: "AutoEnable=true"
  tags:
    - bluetooth
