---
- name: Install spicetify
  kewlfft.aur.aur:
    use: yay
    name: spicetify-cli
  become: true
  become_user: aur_builder

- name: Own spotify install
  file:
    path: /opt/spotify
    owner: "{{ user.name }}"
    recurse: true

- name: Initialize spicetify
  command:
    cmd: spicetify
    creates: "/home/{{ user.name }}/.config/spicetify"
  become_user: "{{ user.name }}"

- name: Check if Spotify initialized
  stat:
    path: "/home/{{ user.name }}/.config/spotify/prefs"
  register: spotify_config

- name: Create spicetify backup
  command:
    cmd: spicetify backup
    creates: "/home/{{ user.name }}/.config/spicetify/Backup/xpui.spa"
  become_user: "{{ user.name }}"
  when: spotify_config.stat.exists

- name: Apply settings
  command:
    cmd: spicetify apply -q
  become_user: "{{ user.name }}"
  when: spotify_config.stat.exists
