---
- name: Install docker
  pacman:
    name: docker
    state: present

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: true
